# CHUK MCP Perplexity Server Configuration
host:
  name: "chuk-mcp-perplexity"
  log_level: "INFO"

server:
  type: "sse"  # Options: stdio, websocket

sse:
  host: "0.0.0.0"
  port: 8020
  sse_path: "/sse"
  message_path: "/messages/"
  log_level: "info"
  access_log: false

mcp_servers:
  perplexity_server:
    enabled: true
    location: "."
    tools:
      enabled: true
      module: "chuk_mcp_perplexity.tools"