# CHUK MCP Perplexity Server Configuration
host:
  name: "chuk-mcp-perplexity"
  log_level: "INFO"

server:
  type: "sse"  # Options: stdio, websocket

mcp_servers:
  perplexity_server:
    enabled: true
    location: "."
    tools:
      enabled: true
      module: "chuk_mcp_perplexity.tools"